version: '3.8'

networks:
  web-net:
    driver: bridge

services:
#  db:
#    image: postgres:15-alpine
#    container_name: db
#    env_file:
#      - db.env

  bot:
    build: .
    container_name: bot
    env_file:
      - develop.env
#    depends_on:
#      - db
